import {describe,it,expect} from 'vitest';
import * as rules from '../src/logic.js';
import {BINS,RECIPES,cookingPose} from '../public/exhibit-data.js';
const L=rules as {setup:(ids:string[])=>any;validateAction:(s:any,id:string,a:any)=>{ok:boolean,error?:string};applyAction:(s:any,id:string,a:any)=>any};
function fixture(){let s=L.setup(['a','b']),now=10000;const act=(a:any,id='a')=>{now+=300;const q={...a,_now:now},v=L.validateAction(s,id,q);expect(v.ok,JSON.stringify(q)+' '+v.error).toBe(true);const previous=s,old=JSON.stringify(s);s=L.applyAction(s,id,q);expect(JSON.stringify(previous)).toBe(old);};const walk=(x:number,z:number,id='a')=>{for(let i=0;i<300;i++){const p=s.players[id],dx=x-p.x,dz=z-p.z,d=Math.hypot(dx,dz);if(d<.01)return;const f=Math.min(1,.8/d);act({kind:'move',dx:dx*f,dz:dz*f,yaw:0},id);}throw Error('walk route exceeded budget');};return {get s(){return s;},set s(value){s=value;},get now(){return now;},act,walk,check:(a:any,id='a')=>L.validateAction(s,id,{...a,_now:now+300})};}
function assemble(f:ReturnType<typeof fixture>,body:string){f.act({kind:'travel',zone:'workshop'});f.walk(110,21);f.act({kind:'selectBody',body});for(const part of RECIPES[body]!){const bin=BINS[part]!;f.walk(bin[0],bin[1]+2);f.act({kind:'takePart',part});f.walk(110,21);f.act({kind:'installPart'});}}
describe('physical workshop',()=>{
 it('builds a dog and humanoid from seven installed modules each',()=>{const f=fixture();assemble(f,'dog');expect(f.s.workshop.installed).toHaveLength(7);expect(f.s.workshop.built.dog).toBeTruthy();assemble(f,'humanoid');expect(Object.keys(f.s.workshop.built)).toEqual(['dog','humanoid']);expect(f.s.players.a.carry).toBeNull();});
 it('allows workshop and cooking immediately without unlocking warehouse finale',()=>{const f=fixture();expect(f.check({kind:'travel',zone:'workshop'}).ok).toBe(true);expect(f.check({kind:'travel',zone:'kitchen'}).ok).toBe(true);expect(f.check({kind:'travel',zone:'warehouse'}).ok).toBe(false);});
 it('refuses pickup at a distance and two parts in one hand',()=>{const f=fixture();expect(f.check({kind:'takePart',part:'brain'}).ok).toBe(false);f.act({kind:'travel',zone:'workshop'});f.walk(103,20);f.act({kind:'takePart',part:'frame'});expect(f.check({kind:'takePart',part:'frame'}).error).toBe('handsFull');});
 it('does not consume a wrong module; G returns it safely',()=>{const f=fixture();f.act({kind:'travel',zone:'workshop'});f.walk(110,21);f.act({kind:'selectBody',body:'dog'});f.walk(117,20);f.act({kind:'takePart',part:'arm'});f.walk(110,21);expect(f.check({kind:'installPart'}).error).toBe('wrongPart');expect(f.s.players.a.carry).toBe('arm');f.act({kind:'returnPart'});expect(f.s.players.a.carry).toBeNull();expect(f.s.workshop.installed).toHaveLength(0);});
 it('permits collaborators to contribute to the same shared body',()=>{const f=fixture();f.act({kind:'travel',zone:'workshop'});f.act({kind:'travel',zone:'workshop'},'b');f.walk(110,21);f.act({kind:'selectBody',body:'dog'});f.walk(103,20);f.act({kind:'takePart',part:'frame'});f.walk(110,21);f.act({kind:'installPart'});f.walk(103,24,'b');f.act({kind:'takePart',part:'leg'},'b');f.walk(110,21,'b');f.act({kind:'installPart'},'b');expect(f.s.workshop.builders).toEqual(['a','b']);expect(f.s.workshop.installed).toEqual(['frame','leg']);});
 it('refuses recipe replacement during construction and remote installation',()=>{const f=fixture();f.act({kind:'travel',zone:'workshop'});f.walk(110,21);f.act({kind:'selectBody',body:'humanoid'});expect(f.check({kind:'selectBody',body:'dog'}).error).toBe('assemblyBusy');f.walk(103,20);f.act({kind:'takePart',part:'frame'});expect(f.check({kind:'installPart'}).error).toBe('closer');});
 it('migrates v2 rooms preserving active demonstrations and learned skills',()=>{const f=fixture();f.s.version=2;f.s.skills=['kitchen'];f.s.experiments={dexterity:{stage:'aligning',step:1}};const n=L.applyAction(f.s,'a',{kind:'migrate'});expect(n.version).toBe(3);expect(n.skills).toEqual(['kitchen']);expect(n.experiments.dexterity.step).toBe(1);expect(n.workshop.installed).toEqual([]);});
});
describe('cooking timeline',()=>{
 it('has distinct pickup, cracking, cooking and plated states',()=>{const start=100000,pick=cookingPose(start+1000,start),crack=cookingPose(start+9500,start),cook=cookingPose(start+16000,start),plate=cookingPose(start+35000,start);expect(pick.whole).toBe(true);expect(pick.foodVisible).toBe(false);expect(crack.halves).toBe(true);expect(crack.stream).toBe(true);expect(cook.steam).toBe(true);expect(plate.plated).toBe(true);expect(plate.foodVisible).toBe(true);expect(plate.food[0]).toBeGreaterThan(cook.food[0]+1);});
 it('keeps the spatula below the egg during transfer',()=>{const p=cookingPose(27000,0);expect(p.food[1]-p.right[1]).toBeCloseTo(.03,5);expect(p.food[0]).toBeCloseTo(p.right[0],5);});
 it('restarts with an authoritative shared timestamp, only from nearby',()=>{const f=fixture();expect(f.check({kind:'cookRestart'}).ok).toBe(false);f.act({kind:'travel',zone:'kitchen'});f.act({kind:'cookRestart'});expect(f.s.kitchenShow.started).toBe(f.now);expect(cookingPose(f.now+9500,f.s.kitchenShow.started)).toEqual(cookingPose(f.now+9500,f.s.kitchenShow.started));});
});
