import {describe,it,expect} from 'vitest';
import * as Rules from '../src/logic.js';
const L=Rules as {setup:(p:string[])=>any;validateAction:(s:any,p:string,a:any)=>{ok:boolean,error?:string};applyAction:(s:any,p:string,a:any)=>any;viewFor:(s:any,p:string)=>any};
function rig(){let state=L.setup(['a','b']),now=10000;const act=(a:any,id='a')=>{now+=300;const q={...a,_now:now};expect(L.validateAction(state,id,q).ok,JSON.stringify(q)).toBe(true);const previous=JSON.stringify(state),next=L.applyAction(state,id,q);expect(JSON.stringify(state)).toBe(previous);state=next;};const walk=(x:number,z:number)=>{let guard=0;while(Math.hypot(state.players.a.x-x,state.players.a.z-z)>.01&&guard++<400){const dx=x-state.players.a.x,dz=z-state.players.a.z,l=Math.hypot(dx,dz),f=Math.min(.8/l,1);act({kind:'move',dx:dx*f,dz:dz*f,yaw:0});}};return {get state(){return state;},set state(s){state=s;},get now(){return now;},act,walk,wait:(ms:number)=>now+=ms};}
function complete(order=['kitchen','dexterity']){const r=rig();for(const station of order){r.walk(station==='kitchen'?-8:8,-1);r.act({kind:'begin',station});if(station==='kitchen')r.act({kind:'record',station});const placements=station==='kitchen'?[[[-.65,-.25],[.6,.4]]]:[[[-.7,-.45],[.5,-.35]],[[-.7,.45],[.5,.35]]];for(const [src,dst]of placements as [number[],number[]][]){r.act({kind:'rig',station,x:src[0],z:src[1]});r.act({kind:'grip',station});r.act({kind:'rig',station,x:dst[0],z:dst[1]});r.act({kind:'grip',station});}r.wait(3100);r.act({kind:'reward',station});}
r.act({kind:'travel',zone:'hills'});r.walk(52,2);r.act({kind:'begin',station:'locomotion'});for(const [x,z]of [[52,-5],[56,-9],[61,-7],[65,-2]] as [number,number][]){r.walk(x,z);r.act({kind:'step',station:'locomotion'});}r.walk(60,-11);r.act({kind:'begin',station:'parkour'});for(const policy of ['balance','reach','soft']){r.act({kind:'policy',station:'parkour',policy});r.act({kind:'step',station:'parkour'});r.wait(2300);r.act({kind:'reward',station:'parkour'});}r.walk(68,6);r.act({kind:'begin',station:'adaptation'});r.act({kind:'damage',station:'adaptation'});r.act({kind:'policy',station:'adaptation',policy:'redistribute'});r.act({kind:'step',station:'adaptation'});r.wait(1800);r.act({kind:'reward',station:'adaptation'});r.act({kind:'travel',zone:'lab'});r.walk(0,-14);r.act({kind:'begin',station:'simulation'});r.wait(2300);r.act({kind:'step',station:'simulation'});r.walk(6,-11);r.act({kind:'step',station:'simulation'});r.wait(1800);r.act({kind:'reward',station:'simulation'});r.act({kind:'travel',zone:'warehouse'});r.walk(110,3);r.act({kind:'deploy',station:'warehouse'});return r.state;}
describe('hands-on robot learning campaign',()=>{
 it('completes all six lessons and deployment deterministically without mutations',()=>{const a=complete(),b=complete();expect(a).toEqual(b);expect(a.skills).toHaveLength(6);expect(a.level).toBe(3);expect(a.deployed).toBe(true);expect(a.experiments.kitchen.trail.length).toBeGreaterThan(3);});
 it('supports a different early lesson order',()=>expect(complete(['dexterity','kitchen']).deployed).toBe(true));
 it('rejects fake pickup, off-target release, and early replay approval',()=>{const r=rig();r.walk(-8,-1);r.act({kind:'begin',station:'kitchen'});r.act({kind:'record',station:'kitchen'});expect(L.validateAction(r.state,'a',{kind:'grip',station:'kitchen',_now:r.now+300}).error).toBe('pickup');r.act({kind:'rig',station:'kitchen',x:-.65,z:-.25});r.act({kind:'grip',station:'kitchen'});expect(L.validateAction(r.state,'a',{kind:'grip',station:'kitchen',_now:r.now+300}).error).toBe('placement');r.act({kind:'rig',station:'kitchen',x:.6,z:.4});r.act({kind:'grip',station:'kitchen'});expect(L.validateAction(r.state,'a',{kind:'reward',station:'kitchen',_now:r.now+300}).error).toBe('observe');});
 it('a wrong gait fails; changing the hypothesis permits recovery',()=>{const r=rig();r.state.skills=['kitchen','dexterity'];r.act({kind:'travel',zone:'hills'});r.walk(60,-11);r.act({kind:'begin',station:'parkour'});for(let i=0;i<3;i++){r.act({kind:'policy',station:'parkour',policy:'reach'});r.act({kind:'step',station:'parkour'});expect(r.state.experiments.parkour.success).toBe(false);r.wait(2400);r.act({kind:'reward',station:'parkour'});}expect(r.state.skills).toHaveLength(2);expect(r.state.experiments.parkour.attempts).toBe(3);r.act({kind:'policy',station:'parkour',policy:'balance'});r.act({kind:'step',station:'parkour'});r.wait(2400);r.act({kind:'reward',station:'parkour'});expect(r.state.experiments.parkour.step).toBe(1);});
 it('requires a correct compensation strategy',()=>{const r=rig();r.state.skills=['kitchen','dexterity'];r.act({kind:'travel',zone:'hills'});r.walk(68,6);r.act({kind:'begin',station:'adaptation'});r.act({kind:'damage',station:'adaptation'});r.act({kind:'policy',station:'adaptation',policy:'speed'});r.act({kind:'step',station:'adaptation'});expect(r.state.experiments.adaptation.stage).toBe('damaged');expect(L.validateAction(r.state,'a',{kind:'reward',station:'adaptation',_now:r.now+3000}).ok).toBe(false);});
 it('humanoid must be led to a real receiving location',()=>{const r=rig();r.state.skills=['kitchen','dexterity','locomotion','parkour','adaptation'];r.walk(0,-14);r.act({kind:'begin',station:'simulation'});r.wait(2300);r.act({kind:'step',station:'simulation'});expect(L.validateAction(r.state,'a',{kind:'step',station:'simulation',_now:r.now+300}).error).toBe('handover');r.walk(6,-11);r.act({kind:'step',station:'simulation'});expect(r.state.experiments.simulation.stage).toBe('handover');});
 it('rejects premature transfer, invalid rig coordinates and non-owner control',()=>{const r=rig();expect(L.validateAction(r.state,'a',{kind:'travel',zone:'warehouse',_now:12000}).ok).toBe(false);r.walk(-8,-1);r.act({kind:'begin',station:'kitchen'});r.act({kind:'record',station:'kitchen'});expect(L.validateAction(r.state,'a',{kind:'rig',station:'kitchen',x:Infinity,z:0,_now:r.now+300}).ok).toBe(false);r.state.players.b.x=-8;r.state.players.b.z=-1;expect(L.validateAction(r.state,'b',{kind:'begin',station:'kitchen',_now:r.now+300}).error).toBe('occupied');});
 it('two engineers can train different bodies without overwriting demonstrations',()=>{const r=rig();r.walk(-8,-1);r.state.players.b.x=8;r.state.players.b.z=-1;r.act({kind:'begin',station:'kitchen'});r.act({kind:'record',station:'kitchen'});r.act({kind:'begin',station:'dexterity'},'b');r.act({kind:'rig',station:'kitchen',x:-.65,z:-.25});r.act({kind:'grip',station:'kitchen'});r.act({kind:'rig',station:'dexterity',x:-.7,z:-.45},'b');r.act({kind:'grip',station:'dexterity'},'b');expect(r.state.experiments.kitchen.gripper.held).toBe(true);expect(r.state.experiments.dexterity.gripper.held).toBe(true);expect(r.state.experiments.kitchen.owner).toBe('a');expect(r.state.experiments.dexterity.owner).toBe('b');expect(r.state.players.a.active).toBe('kitchen');expect(r.state.players.b.active).toBe('dexterity');});
 it('migrates a v1 room without losing learned skills',()=>{const r=rig();r.state.version=1;r.state.skills=['kitchen','dexterity'];const next=L.applyAction(r.state,'a',{kind:'migrate'});expect(next.version).toBe(3);expect(next.skills).toEqual(['kitchen','dexterity']);expect(next.level).toBe(2);});
});
