import {SELF} from 'cloudflare:test';
import {describe,it,expect} from 'vitest';
async function open(room:string,id:string){const res=await SELF.fetch(`https://game.test/ws/${room}`,{headers:{Upgrade:'websocket'}});expect(res.status).toBe(101);const ws=res.webSocket!;ws.accept();const frames:any[]=[];ws.addEventListener('message',(e:MessageEvent)=>{try{frames.push(JSON.parse(String(e.data)));}catch{}});const next=async(pred:(f:any)=>boolean)=>{for(let i=0;i<200;i++){const n=frames.find(pred);if(n)return n;await scheduler.wait(10);}throw Error('Frame timeout '+JSON.stringify(frames));};ws.send(JSON.stringify({type:'join',playerId:id}));await next(f=>f.type==='state');return {ws,frames,next,send:(action:any)=>ws.send(JSON.stringify({type:'action',action}))};}
const unique=()=>crypto.randomUUID().slice(0,12);
describe('OMNI co-op room',()=>{
 it('starts alone; late collaborator receives a real player body',async()=>{const room=unique(),a=await open(room,'alice'),b=await open(room,'bob');const f=await b.next(f=>f.view?.players?.bob);expect(f.status).toBe('playing');expect(Object.keys(f.view.players)).toEqual(['alice','bob']);a.ws.close();b.ws.close();});
 it('broadcasts authoritative movement and retains it after refresh',async()=>{const room=unique(),a=await open(room,'alice'),b=await open(room,'bob');a.frames.length=b.frames.length=0;a.send({kind:'move',dx:.5,dz:0,yaw:1});const f=await b.next(f=>f.view?.players.alice.x===.5);expect(f.view.players.alice.yaw).toBe(1);a.ws.close();const restored=await open(room,'alice');const r=await restored.next(f=>f.view?.players.alice.x===.5);expect(r.seats).toEqual(['alice','bob']);b.ws.close();restored.ws.close();});
 it('fifth visitor spectates and cannot act or reset',async()=>{const room=unique(),people=[];for(let i=0;i<5;i++)people.push(await open(room,'p'+i));const s=people[4]!;s.frames.length=0;s.send({kind:'move',dx:.1,dz:0,yaw:0});expect((await s.next(f=>f.type==='error')).error).toBe('spectators cannot act');s.frames.length=0;s.ws.send(JSON.stringify({type:'reset'}));expect((await s.next(f=>f.type==='error')).error).toBe('spectators cannot reset');people.forEach(p=>p.ws.close());});
 it('rejects teleport, reward spoof, identity registration and injected clock',async()=>{const a=await open(unique(),'a');a.frames.length=0;a.send({kind:'move',dx:100,dz:0,yaw:0});expect((await a.next(f=>f.type==='error')).error).toBe('movement');a.frames.length=0;a.send({kind:'reward',station:'kitchen',_now:1e15});expect((await a.next(f=>f.type==='error')).error).toBe('closer');a.frames.length=0;a.send({kind:'register'});expect((await a.next(f=>f.type==='error')).error).toBe('invalid action');a.ws.close();});
 it('echoes timing probes only to the sender and uses a server clock',async()=>{const room=unique(),a=await open(room,'a'),b=await open(room,'b');a.frames.length=b.frames.length=0;a.send({kind:'move',dx:.5,dz:0,yaw:0,_stamp:123,_now:1e15});const own=await a.next(f=>f.echo===123);expect(own.serverTime).toBeLessThan(1e15);const other=await b.next(f=>f.view?.players.a.x===.5);expect(other.echo).toBeUndefined();a.ws.close();b.ws.close();});
 it('isolates rooms and resets shared state',async()=>{const a=await open(unique(),'a'),b=await open(unique(),'b');a.send({kind:'move',dx:.5,dz:0,yaw:0});await a.next(f=>f.view?.players.a.x===.5);expect(b.frames[0].view.players.b.x).toBe(0);a.frames.length=0;a.ws.send(JSON.stringify({type:'reset'}));const f=await a.next(f=>f.type==='state');expect(f.view.players.a.x).toBe(0);expect(f.view.skills).toEqual([]);a.ws.close();b.ws.close();});
});
